//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTIDAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaEmpleado
    {
        public int idSalidaEmpleado { get; set; }
        public int idEmpleado { get; set; }
        public string TipoSalida { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaSalida { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
